### ISSUE TITLE
Low quality Lain

### ISSUE THREAD

**Issue by itzyboi** [Damp-Cuttlefish/GDPClient#2] opened 2016-02-15 13:44 UTC
Please improve the quality of your lain, it's pretty horrible to look at every time i log in and try to do something

**Comment by Damp-Cuttlefish** [comment] 2016-02-15 13:45
This lain is part of my identity and I won't have you slandering it. Issue marked as invalid, working as intended.

**Comment by itzyboi** [comment] 2016-02-15 13:46
@FriarOmelette please back me up here, he won't listen to me

**Comment by Damp-Cuttlefish** [comment] 2016-02-15 13:48
It's not a bug, it's a feature.

**Closed as completed** 2016-02-15 13:57 UTC
Labels: enhancement, invalid, wontfix
